# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Tests
on:
  push:
    branches:
      - master

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        # The following issue on pytest-cookies is preventing the tests to run correctly
        # on windows. Until then, we want to not run the tests on windows
        # https://github.com/hackebrot/pytest-cookies/issues/62
        os: [ubuntu-latest, macOS-latest] #  windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Initialize project
        run: |
          make init
      - name: Run ci tests
        run: |
          make ci
      - name: Build package
        run: |
          make build
